### PR TITLE
feat: add Shutdown to support graceful quit of HTTP Server

### PR DESCRIPTION
**Pull request by zxdstyle**
## 📑 Description

[Closes https://github.com/goravel/goravel/issues/436](https://github.com/goravel/goravel/issues/436)

@coderabbitai summary

## ✅ Checks

- [ ] Added test cases for my code

### CODE REVIEW

**Review by hwbrzzl — COMMENTED** [review]
In the previous PR, I said we need to change `Singleton` to `Bind`. I reviewed it, and it's wrong (sorry for this). The Route facade should be a singleton instance, because Routers are registered to the Route facade. If so, in order to adapt the situation of calling `Run` and `RunTLS` simultaneously, the `server` may need to change to `[]*http.Server` from `*http.Server` in this PR: https://github.com/goravel/gin/pull/83/files , close all servers at the same time when calling the `Shutdown` method. Any thoughts, please?

**Comment by zxdstyle** [comment]
> In the previous PR, I said we need to change `Singleton` to `Bind`. I reviewed it, and it's wrong (sorry for this). The Route facade should be a singleton instance, because Routers are registered to the Route facade. If so, in order to adapt the situation of calling `Run` and `RunTLS` simultaneously, the `server` may need to change to `[]*http.Server` from `*http.Server` in this PR: https://github.com/goravel/gin/pull/83/files , close all servers at the same time when calling the `Shutdown` method. Any thoughts, please?

I still think it is not suitable to use slice to manage server instances. In practice, there are usually no multiple instances at the same time. Mounting multiple http servers on the struct is also more convenient to manage than slice. More situations that need to consider multiple server instances are: different host, port and routes. In this case, maybe need to open a separate facade to create a new route instance. The default facade.Route() is associated with too many things.

**Comment by hwbrzzl** [comment]
Emm, another facade is unexpected. And yes, there are usually no multiple instances at the same time. Maybe we can add a new method: `facades.Route().Host()` or something else in the future, didn't think carefully. But for now, User can use `Run`, `RunTLS` simultaneously, so we have to deal with this situation.

**Comment by zxdstyle** [comment]
@hwbrzzl has compatibled https://github.com/goravel/gin/pull/83

**Review by hwbrzzl — APPROVED** [review]
Great PR 👍

**Comment by hwbrzzl** [comment]
Hey @zxdstyle   We created a private channel in Discord for contributors. You can click [the link](https://discord.gg/dMs73mSa) and DM me (@Bowen) to join it if you are interested.

Here you can:

1. Send PR link or review others' PRs;
2. Discuss new features before creating an issue;
3. Vote for something;
4. etc.

**Pull request merged**
