### PR TITLE
feat: add OrWhereNull method

### PR DESCRIPTION
**Pull request by Kamandlou**
## 📑 Description
add OrWhereNull method

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by hwbrzzl** [comment]
Thanks, CI failed.

**Comment by Kamandlou** [comment]
All tests are passed on my local computer.

 I don't know why CI failed here

@hwbrzzl

**Review by hwbrzzl — APPROVED** [review]
CI passed, just rerun them. Thanks!

**Comment by hwbrzzl** [comment]
Thanks a lot, bro, you finished many PRs and helped Orm add many useful methods. I wonder if you are interested in finishing two features and then becoming a core contributor? Just by the way, it's up to you, whatever the answer, I appreciate that. For detail: https://www.goravel.dev/prologue/contributions.html

**Comment by Kamandlou** [comment]
Thank you for your kind words, bro! Your appreciation means a lot to me. I’m glad I could contribute to Orm by finishing PRs and adding useful methods. As for the offer to work on two features and become a core contributor, I truly appreciate the opportunity. I’ll definitely check out the details at this link. Whether I decide to take it up or not, I’m grateful for your trust and encouragement

**Pull request merged**
