### PR TITLE
fix: [#229] media file not parsing correctly

### PR DESCRIPTION
**Pull request by hwbrzzl**
Closes https://github.com/goravel/goravel/issues/229

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Review by DevHaoZi — APPROVED** [review]

**Comment by DevHaoZi** [comment]
@hwbrzzl Codecov seems token error, please help to check it.

**Comment by DevHaoZi** [comment]
> @hwbrzzl Codecov seems token error, please help to check it.

image

**Comment by hwbrzzl** [comment]
But I rerun the CI again, it passed, so strange.

**Comment by DevHaoZi** [comment]
> But I rerun the CI again, it passed, so strange.

Check the status page `https://app.codecov.io/gh/goravel/framework/commits`, it hasn't been updated for several says.

**Comment by hwbrzzl** [comment]
Make sense, let me check it.

**Comment by hwbrzzl** [comment]
Fixed, the token error.

**Pull request merged**
