### PR TITLE
feat: add some options for mail

### PR DESCRIPTION
**Pull request by hwbrzzl**
## 📑 Description

1. Add some options, User doesn't need to import contracts/mail anymore;
2. Modify `From` to `Address`, more suitable;

Modify the way `Subject` is set:

```go
-- import "github.com/goravel/framework/contracts/mail"
++ import "github.com/goravel/framework/mail"

-- Content(mail.Content{Subject: "Subject", Html: "<h1>Hello Goravel</h1>"})
++ Content(mail.Html("<h1>Hello Goravel</h1>")).Subject("Subject")
```

If you are using the `From` method:

```go
-- import "github.com/goravel/framework/contracts/mail"
++ import "github.com/goravel/framework/mail"

-- From(mail.From{Address: testFromAddress, Name: testFromName}
++ From(mail.Address(testFromAddress, testFromName)
```

If you are using the `Queue` method:

```go
-- import "github.com/goravel/framework/contracts/mail"
++ import "github.com/goravel/framework/mail"

-- Queue(mail.Queue{Connection: "high", Queue: "mail"})
++ Queue(mail.Queue().Connection("high").Queue("mail"))
```

## Summary by CodeRabbit

- **New Features**
	- Introduced a more intuitive way to handle email sender information, renaming `From` to `Address`.
	- Added functions for streamlined creation of addresses and HTML content for emails.
	- Introduced a `QueueMail` struct to manage email queuing operations.

- **Improvements**
	- Enhanced clarity in variable names, such as changing `attaches` to `attachments`.
	- Improved readability and maintainability of the email interface and application methods.

- **Tests**
	- Increased timeout duration for email tests to ensure reliability.
	- Added new test case for validating email sending through specific connections.

## ✅ Checks

- [x] Added test cases for my code

### CODE REVIEW

**Comment by kkumar-gcc** [comment]
> Add some options, User doesn't need to import contracts/mail anymore;

But user still need to import `mail`.

**Comment by hwbrzzl** [comment]
> > Add some options, User doesn't need to import contracts/mail anymore;
> 
> But user still needs to import `github.com/goravel/framework/mail`.

Where? For example?

**Comment by kkumar-gcc** [comment]
> > > Add some options, User doesn't need to import contracts/mail anymore;
> > 
> > 
> > But user still needs to import `github.com/goravel/framework/mail`.
> 
> Where? For example?

image

**Comment by hwbrzzl** [comment]
Yes, `github.com/goravel/framework/mail` is required.

**Review by kkumar-gcc — APPROVED** [review]
LGTM

**Pull request merged**
