### PR TITLE
Exceptions

### PR DESCRIPTION
**Pull request by ahmed3mar**
Closes # 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by hwbrzzl** [comment]
Hi @ahmed3mar Could you please write your idea about this here first? I'm not sure if we need this feature.

**Comment by hwbrzzl** [comment]
We can discuss [here](https://github.com/goravel/goravel/issues) first in the future before doing a new feature.

**Comment by ahmed3mar** [comment]
> Hi @ahmed3mar Could you please write your idea about this here first? I'm not sure if we need this feature.

It's to catch all exceptions and manipulate them and the return response depends on the exception

added ```AbortWithError``` we will path error or exception to it and render specific response message and code depending on the error we can do it in ```app/exceptions/handler.go``` just like Laravel exceptions

also there is ```Recover``` middleware which will report to same handler and in handler we can report to sentry or any thing

**Comment by hwbrzzl** [comment]
Thanks for your reply! Can you please add some examples for this feature? Sorry, I'm not very clear if just looking at the code.

**Comment by ahmed3mar** [comment]
You can find it here
https://github.com/ahmed3mar/goravel/pull/1

**Comment by hwbrzzl** [comment]
Okay, I saw. Could you please add more examples of how to use `facades.Exception()`?

**Comment by ahmed3mar** [comment]
> Okay, I saw. Could you please add more examples of how to use `facades.Exception()`?

I think we can remove it we can catch the error from AbortWithError and panic using recover middleware

**Comment by hwbrzzl** [comment]
For example? The code when using in goravel/goravel.

**Comment by hwbrzzl** [comment]
Hi @ahmed3mar Are you still dealing with this PR, please?

**Comment by hwbrzzl** [comment]
Closed this PR first, feel free to reopen it if needed.

**Pull request closed without merging**
