### PR TITLE
feat: add new ChopEnd and ChopStart string helpers

### PR DESCRIPTION
**Pull request by shayan-yousefi**
## 📑 Description
In this pull request, I have added two new string helper methods, chopStart and chopEnd, to Goravel. These methods are inspired by the corresponding Laravel string helpers.

For more details, refer to the official Laravel documentation: [String Helpers - chopStart and chopEnd](https://laravel.com/docs/11.x/strings#method-str-chop-start).

## Summary by CodeRabbit

- **New Features**
	- Introduced `ChopEnd` method to remove specified strings from the end of a string.
	- Introduced `ChopStart` method to remove specified strings from the beginning of a string.
  
- **Tests**
	- Added `TestChopStart` to validate the behavior of the `ChopStart` method.
	- Added `TestChopEnd` to validate the behavior of the `ChopEnd` method.

## ✅ Checks

- [x] Added test cases for my code

### CODE REVIEW

**Review by hwbrzzl — CHANGES_REQUESTED** [review]
They seem the same as `LTrim` and `RTrim`. Are they?

**Comment by shayan-yousefi** [comment]
> They seem the same as `LTrim` and `RTrim`. Are they?

ChopStart and ChopEnd can remove one or more strings from the left or right end, respectively, whereas Ltrim and Rtrim always remove a single string.

I committed another change to do trim with Golang built-in TrimLeft and TrimRight functions

**Comment by hwbrzzl** [comment]
Got it, one more question, I noticed this PR is going to merged to v1.14.x, but we only release new versions to fix bug. Do you have any special needs, please?

**Comment by shayan-yousefi** [comment]
> Got it, one more question, I noticed this PR is going to merged to v1.14.x, but we only release new versions to fix bug. Do you have any special needs, please?

May I be wrong? I read documentation for contribute, saw:
Minor features that are fully backward compatible with the current release may be sent to the latest stable branch.

But this was my question too, should I open it on the master?

**Comment by hwbrzzl** [comment]
Sure, please use the master branch. Sorry for the confusion, I'll update the guide.

**Comment by shayan-yousefi** [comment]
> Sure, please use the master branch. Sorry for the confusion, I'll update the guide.

thanks, I changed the base branch to master.

**Comment by kkumar-gcc** [comment]
@shayan-yousefi It would be better if you can add these methods at their alphabetical position.

**Comment by shayan-yousefi** [comment]
> @shayan-yousefi It would be better if you can add these methods at their alphabetical position.

@kkumar-gcc done ✅

**Review by kkumar-gcc-meesho — APPROVED** [review]
Great PR!! Thanks for your contribution.

**Review by kkumar-gcc — APPROVED** [review]
Great PR!! Thanks for your contribution.

**Review by hwbrzzl — APPROVED** [review]
Great PR 👍 Added you to the contributor list.

**Comment by hwbrzzl** [comment]
Looking forward to more PRs from you 👍

**Pull request merged**
