### PR TITLE
feat(support): Added `convert` package

### PR DESCRIPTION
**Pull request by flc1125**
## 📑 Description

- `convert.Tap(...)`
- `convert.With(...)`
- `convert.Transform(...)`
- `convert.Default(...)`

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

Added `convert` package in `support`

### CODE REVIEW

**Review by hwbrzzl — CHANGES_REQUESTED** [review]
A great PR, only one problem, the package name is a bit common, could we find a better package name? Like other: `str`, `time`, etc.

**Comment by flc1125** [comment]
`hlp`? Short for `helpers`. Or is there a better suggestion?

- hlp
- util
- fn
- fns
- ……

**Comment by hwbrzzl** [comment]
@flc1125 I have [a PR](https://github.com/goravel/framework/pull/439/files#diff-21c8332c1d138142732cec56ae66d8a7a56a6c698df3de7434e0eda2e5e82db4R3) that adds a similar function, I put `Pointer` into the `convert` package, how about the `Tap`, `With`, etc?

image

**Comment by flc1125** [comment]
@hwbrzzl It's okay, I can migrate to `convert`.

Then which one between `Ptr` and `Pointer` should I keep?

**Reference:**

- https://github.com/xanzy/go-gitlab/blob/main/types.go#L31-L34

**Comment by hwbrzzl** [comment]
I think `Pointer` is clearer, User doesn't need to memory the short name.

**Comment by flc1125** [comment]
> I think `Pointer` is clearer, User doesn't need to memory the short name.

Adjusted.

**Comment by hwbrzzl** [comment]
Hey @flc1125   We created a private channel in Discord for contributors. You can click [the link](https://discord.gg/dMs73mSa) and DM me (@Bowen) to join it if you are interested.

Here you can:

1. Send PR link or review others' PRs;
2. Discuss new features before creating an issue;
3. Vote for something;
4. etc.

**Comment by flc1125** [comment]
> Hey @flc1125 We created a private channel in Discord for contributors. You can click [the link](https://discord.gg/dMs73mSa) and DM me (@bowen) to join it if you are interested.
> 
> Here you can:
> 
> 1. Send PR link or review others' PRs;
> 2. Discuss new features before creating an issue;
> 3. Vote for something;
> 4. etc.

Thank you for the invitation, I will join.

**Pull request merged**
