### PR TITLE
chore: temporarily fix pterm and lint

### PR DESCRIPTION
**Pull request by devhaozi**
## 📑 Description

Closes https://github.com/goravel/goravel/issues/?

@coderabbitai summary

## ✅ Checks

- [x] Added test cases for my code

### CODE REVIEW

**Review by hwbrzzl — COMMENTED** [review]
Can we upgrade pterm in this PR? To confirm if CI will pass.

**Comment by hwbrzzl** [comment]
Oh, sorry, just found that PR had been merged.

**Comment by hwbrzzl** [comment]
What's the difference between contains `env.IsTesting()` or not?

**Comment by devhaozi** [comment]
> What's the difference between contains `env.IsTesting()` or not?

No different, If use `IsTesting`, the method will still broken in non-test usecase.

**Review by kkumar-gcc — APPROVED** [review]
LGTM

**Pull request merged**
